export const en = {
  // Header
  navHome: 'Home',
  navGenerator: 'Generator',
  navGallery: 'Gallery',
  navAbout: 'About',
  startNow: 'Start Now',
  
  // Footer
  footerAbout: 'About',
  footerPrivacy: 'Privacy Policy',
  footerContact: 'Contact',
  footerRights: 'All rights reserved.',

  // Home Page
  homeHeroTitle1: 'Turn your product photo into a',
  homeHeroTitle2: 'professional ad in seconds.',
  homeHeroSubtitle: 'Upload your product, choose your style, and let our AI design high-quality promotional images ready for any platform.',
  homeUploadButton: 'Upload Your Product',
  feature1Title: 'AI-Powered Scenes',
  feature1Desc: 'Our smart AI creates stunning, realistic ad scenes that make your product shine.',
  feature2Title: 'For Any Product',
  feature2Desc: 'Perfect for clothes, cosmetics, gadgets, and more. If you can sell it, we can style it.',
  feature3Title: 'Fast & High-Quality',
  feature3Desc: 'Get realistic, high-resolution results in seconds, not hours. Ready to post instantly.',

  // Generator Page
  generatorTitle: 'Create Your Ad',
  generatorSubtitle: 'Follow these simple steps to generate your professional product ad.',
  step1: '1. Upload Product Image',
  step2: '2. Choose Options',
  step3: '3. Generate',
  uploadBoxTitle: 'Drag & Drop your product photo',
  uploadBoxSubtitle: 'or click to browse',
  uploadBoxSupports: 'Supports: JPG, PNG',
  removeImage: 'Remove image',
  adType: 'Ad Type',
  adStyle: 'Ad Style',
  generateButton: 'Generate Ad',
  generatingButton: 'Generating your ad...',
  errorUpload: 'Please upload a product image first.',
  errorGenerate: 'Failed to generate ad. Please try again.',
  
  // Ad Types & Styles (from enums)
  'Product Only': 'Product Only',
  'With Male Model': 'With Male Model',
  'With Female Model': 'With Female Model',
  'Instagram Ad': 'Instagram Ad',
  'Store Banner': 'Store Banner',
  'Natural Background': 'Natural Background',

  // Result Page
  resultTitle: 'Your Ad is Ready!',
  resultSubtitle: 'Here is the professional ad generated by our AI. You can download it, share it, or go back to create a new one.',
  resultNote: 'Generated with cutting-edge AI image technology.',
  downloadButton: 'Download Image',
  regenerateButton: 'Regenerate',
  shareButton: 'Share on Instagram',
  shareAlert: 'Share functionality coming soon!',

  // Gallery Page
  galleryTitle: 'Example Showcase',
  gallerySubtitle: 'See what our AI can create. Here are some sample ads generated for various products.',
  galleryLabel: (seconds: number) => `Ad created in ${seconds} seconds.`,

  // About Page
  aboutTitle: 'About Rosha AI',
  aboutP1: '<strong>Rosha AI</strong> was born from a simple idea: empower sellers, marketers, and creators to produce professional-grade ad visuals without the need for a professional designer or complex software.',
  aboutP2: "In today's fast-paced digital market, high-quality visuals are crucial for capturing attention. However, creating these visuals can be time-consuming, expensive, and technically challenging. We wanted to change that.",
  aboutP3: 'Our tool leverages cutting-edge generative AI to bridge the gap between a simple product photo and a polished, ready-to-use advertisement. Just upload your product, select a few options, and our AI instantly crafts a compelling scene around it.',
  aboutP4: "Whether you're a small business owner on a budget, a social media manager needing fresh content, or an e-commerce brand looking to scale your creatives, Rosha AI is designed to be your instant, on-demand visual designer.",

  // Not Found Page
  notFoundTitle: '404',
  notFoundSubtitle: 'Page not found',
  notFoundDesc: 'Sorry, we couldn’t find the page you’re looking for.',
  notFoundButton: 'Go back home',
};
